name: ProtectionCore
version: '1.0'
main: de.justin.protectioncore.ProtectionCore
api-version: '1.20'
softdepend:
  - Multiverse-Core
  - LightWorlds
  - WorldGuard
commands:
  pcinfo:
    permission: protectioncore.info
permissions:
  protectioncore.break:
    default: op
  protectioncore.info:
    default: op
